default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>

development:
  <<: *default
  database: trails_development

test:
  <<: *default
  database: trails_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV["POSTGRES_DB"] %>
    username: <%= ENV["POSTGRES_USER"] %>
    password: <%= ENV["TRAILS_DATABASE_PASSWORD"] %>
    host: <%= ENV["POSTGRES_HOST"] %>
    port: <%= ENV["POSTGRES_PORT"] %>
  cable:
    <<: *primary_production
    database: trails_cable
    migrations_paths: db/cable_migrate
  queue:
    <<: *primary_production
    database: trails_queue
    migrations_paths: db/queue_migrate
  cache:
    <<: *primary_production
    database: trails_cache
    migrations_paths: db/cache_migrate